export interface Persona {
  key: string;
  archetype: string;
  name: string;
  role: string;
  weight_pct: number;
  background: string;
  evaluation_lens: string;
  image: string;
  isRepresentative: boolean;
}

export interface AudiencePanel {
  key: string;
  label: string;
  personas: Persona[];
  image: string;
}

const seed_investors: AudiencePanel = {
  key: "seed_investors",
  label: "Seed Investors",
  image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/seed invest.png",
  personas: [
    {
      key: "yc_p1",
      archetype: "YC Partner",
      name: "Marcus Chen",
      role: "Partner, YC",
      weight_pct: 10.8,
      background: "YC partner, 8 years, backed 200+ companies across B2B SaaS and developer tools. Stanford CS. Former founder.",
      evaluation_lens: "Evaluates founder-market fit, market size credibility, product differentiation, and team completeness. Highest weight on team and market.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/YC partner.png",
      isRepresentative: true,
    },
    {
      key: "yc_p2",
      archetype: "YC Partner",
      name: "Sarah Okonkwo",
      role: "Partner, YC (B2B Focus)",
      weight_pct: 8.6,
      background: "YC partner specialising in B2B software. Previously operator at Stripe and Twilio. MBA Wharton.",
      evaluation_lens: "Weights GTM motion and enterprise readiness heavily. Sceptical of pure PLG without clear enterprise path.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "angel_p1",
      archetype: "Angel Investor",
      name: "Priya Desai",
      role: "Angel, former SaaS Founder",
      weight_pct: 9.7,
      background: "Sold B2B legal workflow company for $45M. Now angels in legal tech and enterprise software.",
      evaluation_lens: "Deep domain expertise in legal workflows. Evaluates product accuracy claims, SMB sales motion, and customer acquisition assumptions with high scrutiny.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/angel with operator background (2).png",
      isRepresentative: true,
    },
    {
      key: "angel_p2",
      archetype: "Angel Investor",
      name: "David Park",
      role: "Angel, ex-Palantir BD",
      weight_pct: 7.5,
      background: "10 years enterprise sales at Palantir. Understands how AI products sell into regulated industries.",
      evaluation_lens: "Evaluates enterprise sales cycle assumptions, security and compliance positioning, and whether the team can close large deals.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "fc_p1",
      archetype: "First-Cheque VC",
      name: "Alex Rivera",
      role: "Pre-seed Partner",
      weight_pct: 8.6,
      background: "First cheque investor, 60+ pre-seed investments. Backs contrarian founders with non-obvious insights.",
      evaluation_lens: "Evaluates narrative sharpness and whether the insight behind the business is genuinely non-obvious. Penalises boilerplate why-now framing.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/first-cheque (1).png",
      isRepresentative: true,
    },
    {
      key: "fc_p2",
      archetype: "First-Cheque VC",
      name: "Nina Sharma",
      role: "Pre-seed, Legal Tech Focus",
      weight_pct: 6.5,
      background: "Pre-seed investor with portfolio in legal tech, compliance, and RegTech. JD from Yale, never practised.",
      evaluation_lens: "Evaluates domain depth, regulatory awareness, and whether the founder understands the legal market's procurement dynamics.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "da_p1",
      archetype: "Devil's Advocate",
      name: "James Whitfield",
      role: "VC Analyst, Due Diligence",
      weight_pct: 9.7,
      background: "Investment analyst at top-tier VC, responsible for finding every flaw before IC meetings. Has killed 40+ deals.",
      evaluation_lens: "Finds mathematical inconsistencies, unsourced claims, and unverifiable metrics. Highest scrutiny on financial projections and market sizing methodology.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/devils advocate.png",
      isRepresentative: true,
    },
    {
      key: "da_p2",
      archetype: "Devil's Advocate",
      name: "Rachel Kim",
      role: "Associate, Competitive Intel",
      weight_pct: 7.5,
      background: "VC associate specialising in competitive landscape analysis. Has mapped the legal AI market exhaustively.",
      evaluation_lens: "Evaluates competitive moat, unnamed competitors, and whether the differentiation claimed would survive a well-funded attack.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "tech_p1",
      archetype: "Technical Co-Investor",
      name: "Omar Hassan",
      role: "Deep Tech Investor",
      weight_pct: 8.6,
      background: "PhD ML Stanford. 15 years between research and investing. Has evaluated 200+ AI companies.",
      evaluation_lens: "Evaluates model architecture, training data quality, accuracy claim methodology, and whether the technical moat is real or reproducible.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/technical co investor.png",
      isRepresentative: true,
    },
    {
      key: "tech_p2",
      archetype: "Technical Co-Investor",
      name: "Aisha Patel",
      role: "NLP Specialist Investor",
      weight_pct: 6.5,
      background: "Former NLP researcher at DeepMind. Invests in applied AI companies with genuine technical differentiation.",
      evaluation_lens: "Evaluates NLP architecture specifics, fine-tuning approach, and whether 'trained on 2M documents' represents a real moat.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "mkt_p1",
      archetype: "Market Skeptic",
      name: "Robert Novak",
      role: "Market Sizing Specialist",
      weight_pct: 8.6,
      background: "Former McKinsey market sizing practice. Has built bottom-up market models for 300+ companies.",
      evaluation_lens: "Rejects top-down TAM/SAM/SOM methodology. Demands bottom-up unit economics and customer count derivation.",
      image: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_dfd08014-4235-462b-8049-fa79247ec7ec.jpg",
      isRepresentative: true,
    },
    {
      key: "mkt_p2",
      archetype: "Market Skeptic",
      name: "Lisa Tanaka",
      role: "Timing & Market Dynamics",
      weight_pct: 7.5,
      background: "Investor focused on market timing. Has seen multiple legal tech waves and knows why previous ones failed.",
      evaluation_lens: "Evaluates whether the timing rationale is genuine or retrofitted, and what specifically makes now different from 3 years ago.",
      image: "",
      isRepresentative: false,
    },
  ],
};

const enterprise_buyers: AudiencePanel = {
  key: "enterprise_buyers",
  label: "Enterprise Buyers",
  image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/enterprise buyers.png",
  personas: [
    {
      key: "vpe_p1",
      archetype: "VP Engineering",
      name: "Tom Bradley",
      role: "VP Eng, 600-person SaaS",
      weight_pct: 11.4,
      background: "VP Engineering at a 600-person B2B SaaS company. Has evaluated 50+ vendor tools. Manages 80 engineers.",
      evaluation_lens: "Evaluates integration complexity, API quality, security model, and whether this genuinely reduces engineering burden.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/vp of engineering.png",
      isRepresentative: true,
    },
    {
      key: "vpe_p2",
      archetype: "VP Engineering",
      name: "Claudia Reyes",
      role: "VP Eng, Series B Startup",
      weight_pct: 9.1,
      background: "VP Engineering at a 120-person Series B. Tight budget, vendor-sceptical, has been burned by AI tools that overpromised.",
      evaluation_lens: "Weights implementation timeline and actual vs. claimed accuracy. Sceptical of AI accuracy claims without methodology.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "cfo_p1",
      archetype: "CFO",
      name: "Richard Walsh",
      role: "CFO, 400-person Tech Company",
      weight_pct: 11.4,
      background: "CFO of a 400-person software company. Manages $2M annual software budget. Evaluates every vendor on TCO.",
      evaluation_lens: "Evaluates total cost of ownership, payback period, and whether the ROI claim survives a finance committee.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/cfo.png",
      isRepresentative: true,
    },
    {
      key: "cfo_p2",
      archetype: "CFO",
      name: "Janet Liu",
      role: "CFO, Pre-IPO SaaS",
      weight_pct: 9.1,
      background: "CFO preparing company for IPO. Cost discipline is paramount. Every vendor contract is scrutinised for contractual risk.",
      evaluation_lens: "Evaluates contract terms, auto-renewal risk, price escalation clauses, and exit provisions.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "ciso_p1",
      archetype: "CISO",
      name: "Derek Stone",
      role: "CISO, Financial Services",
      weight_pct: 11.4,
      background: "CISO at a financial services company. Has rejected 30+ vendors for failing security review. SOC 2 and ISO 27001 non-negotiable.",
      evaluation_lens: "Evaluates data residency, encryption at rest and in transit, access controls, compliance certifications, and breach liability.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/ciso.png",
      isRepresentative: true,
    },
    {
      key: "ciso_p2",
      archetype: "CISO",
      name: "Maya Chen",
      role: "CISO, Healthcare Tech",
      weight_pct: 9.1,
      background: "CISO in healthcare. Understands regulated data environments. Contract data contains highly sensitive business information.",
      evaluation_lens: "Evaluates data handling for sensitive contract content, third-party subprocessor risk, and incident response procedures.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "proc_p1",
      archetype: "Procurement Lead",
      name: "Anne Fischer",
      role: "Head of Procurement",
      weight_pct: 10.2,
      background: "Head of procurement at a 500-person company. Has negotiated 200+ vendor contracts. Knows every lock-in tactic.",
      evaluation_lens: "Evaluates pricing transparency, lock-in mechanisms, data portability, exit rights, and whether the proposal gives the buyer leverage.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/procurement lead.png",
      isRepresentative: true,
    },
    {
      key: "eu_p1",
      archetype: "End User",
      name: "Carlos Mendez",
      role: "In-house Counsel, 80-person Tech Co.",
      weight_pct: 10.2,
      background: "Solo in-house lawyer at a fast-growing tech company. Reviews 40+ contracts per month. Technically comfortable.",
      evaluation_lens: "Evaluates whether the product actually fits into his workflow, whether the AI output is trustworthy enough to act on, and whether it saves real time.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/end user.png",
      isRepresentative: true,
    },
    {
      key: "eu_p2",
      archetype: "End User",
      name: "Sophie Laurent",
      role: "Legal Ops Manager",
      weight_pct: 9.1,
      background: "Legal operations manager at a 200-person company. Manages contract lifecycle and vendor relationships.",
      evaluation_lens: "Evaluates workflow integration, output format, collaboration features, and whether junior team members can use this without supervision.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "eu_p3",
      archetype: "End User",
      name: "Ben Okafor",
      role: "Senior Associate, In-house Legal",
      weight_pct: 9.1,
      background: "Senior legal associate who currently does most of the contract review manually. Resistant to tools that create more work.",
      evaluation_lens: "Evaluates whether the output requires heavy verification, whether the UI is actually faster than manual review, and whether it will embarrass him if it's wrong.",
      image: "",
      isRepresentative: false,
    },
  ],
};

const hiring_managers: AudiencePanel = {
  key: "hiring_managers",
  label: "Hiring Managers at Tech Companies",
  image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/hiring managers.png",
  personas: [
    {
      key: "em_p1",
      archetype: "Engineering Manager",
      name: "Steve Holloway",
      role: "Senior EM, FAANG",
      weight_pct: 13.2,
      background: "Senior engineering manager at a major tech company. Reviews 300+ resumes per year. Pattern-matches instantly to strong candidates.",
      evaluation_lens: "Evaluates technical depth, ownership evidence, and whether impact claims are specific and credible.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/senior engineering manager.png",
      isRepresentative: true,
    },
    {
      key: "em_p2",
      archetype: "Engineering Manager",
      name: "Rachel Torres",
      role: "EM, Series B Startup",
      weight_pct: 11.8,
      background: "Engineering manager at a 150-person startup. Hires for generalist engineers who can wear multiple hats.",
      evaluation_lens: "Evaluates breadth vs. depth balance, startup readiness signals, and whether the candidate has operated in ambiguous environments.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "hr_p1",
      archetype: "HR Screener",
      name: "Diane Foster",
      role: "HR Screener, Volume Hiring",
      weight_pct: 11.8,
      background: "HR screener processing 150 resumes per week for a high-growth company. 10-second skim discipline.",
      evaluation_lens: "Evaluates baseline requirements match, formatting clarity, red flag detection, and ATS keyword optimisation.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/hr screener.png",
      isRepresentative: true,
    },
    {
      key: "hr_p2",
      archetype: "HR Screener",
      name: "Mark Jensen",
      role: "Talent Coordinator",
      weight_pct: 9.2,
      background: "Junior talent coordinator doing first-pass filtering. Passes resumes to hiring manager based on explicit criteria only.",
      evaluation_lens: "Strict criteria matching. If the requirement isn't clearly met on the page, fails the candidate.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "peer_p1",
      archetype: "Peer Teammate",
      name: "Priya Kapoor",
      role: "Senior Software Engineer",
      weight_pct: 11.8,
      background: "Senior SWE who has participated in 30+ hiring loops. Informal veto power. Values intellectual honesty.",
      evaluation_lens: "Evaluates whether described projects show genuine technical judgment, and whether the candidate would make her better at her job.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/potential temmate.png",
      isRepresentative: true,
    },
    {
      key: "peer_p2",
      archetype: "Peer Teammate",
      name: "Jason Wu",
      role: "Staff Engineer",
      weight_pct: 10.5,
      background: "Staff engineer who built the team's core infrastructure. Highly sceptical of resume language that sounds impressive but describes commodity work.",
      evaluation_lens: "Evaluates technical specificity, evidence of systems thinking, and whether the impact numbers are plausible given the described role.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "skip_p1",
      archetype: "Skip Director",
      name: "Carmen Alvarez",
      role: "Director of Engineering",
      weight_pct: 11.8,
      background: "Director managing 4 teams. Evaluates candidates two levels below. Cares about long-term leadership trajectory.",
      evaluation_lens: "Evaluates scope growth trajectory, evidence of cross-functional influence, and whether the candidate shows signs of future leadership.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/skip-level director (1).png",
      isRepresentative: true,
    },
    {
      key: "rec_p1",
      archetype: "Recruiter",
      name: "Mike Lawson",
      role: "Technical Recruiter, Agency",
      weight_pct: 10.5,
      background: "External technical recruiter placing 60 engineers per year. Has seen this resume against 500 similar ones this quarter.",
      evaluation_lens: "Evaluates competitive positioning, ATS optimisation, career narrative clarity, and likely interview pass rate.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/recruiter (1).png",
      isRepresentative: true,
    },
    {
      key: "rec_p2",
      archetype: "Recruiter",
      name: "Tanya Brooks",
      role: "In-house Recruiter, Growth Stage",
      weight_pct: 9.2,
      background: "Internal recruiter at a Series C company. Measures herself on time-to-offer and candidate quality.",
      evaluation_lens: "Evaluates whether this candidate would pass the hiring manager's phone screen, and whether the resume gives her enough to sell the candidate internally.",
      image: "",
      isRepresentative: false,
    },
  ],
};

const series_a_investors: AudiencePanel = {
  key: "series_a_investors",
  label: "Series A Investors",
  image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/series A.png",
  personas: [
    {
      key: "lp_p1",
      archetype: "Lead Partner",
      name: "Catherine Voss",
      role: "Lead Partner, Series A Fund",
      weight_pct: 12,
      background: "Lead partner at a $400M Series A fund. Has led 35 deals. Sets the bar for investment committee approval.",
      evaluation_lens: "Evaluates PMF evidence rigorously, growth trajectory sustainability, GTM scalability, and team completeness for this stage.",
      image: "https://miaoda-conversation-file.s3cdn.medo.dev/user-bkod68nngr28/app-bn2wrjsgz11d/20260518/Lead Partner.png",
      isRepresentative: true,
    },
    {
      key: "lp_p2",
      archetype: "Lead Partner",
      name: "Daniel Cho",
      role: "Managing Director, Enterprise Focus",
      weight_pct: 10.8,
      background: "MD at a fund specialising in enterprise software. Has led 20 Series A deals in B2B. Deep GTM pattern recognition.",
      evaluation_lens: "Weights enterprise GTM maturity heavily. Evaluates whether the team can build and manage an enterprise sales function.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "assoc_p1",
      archetype: "Associate",
      name: "Hannah Pierce",
      role: "Investment Associate",
      weight_pct: 10.8,
      background: "Investment associate writing the full investment memo. Will surface every risk, inconsistency, and assumption gap.",
      evaluation_lens: "Exhaustive diligence focus. Finds every number that doesn't reconcile, every claim without a source, every assumption without a test.",
      image: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_ed9bc0d9-5f9d-4942-a72d-f3872190e711.jpg",
      isRepresentative: true,
    },
    {
      key: "assoc_p2",
      archetype: "Associate",
      name: "Felix Nguyen",
      role: "Associate, Market Research",
      weight_pct: 8.4,
      background: "Associate focused on market research and competitive mapping. Has built competitor matrices for 50+ deals.",
      evaluation_lens: "Evaluates named and unnamed competitors, differentiation sustainability, and whether the competitive slide represents the full landscape.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "pf_p1",
      archetype: "Portfolio Founder",
      name: "Isabelle Martin",
      role: "Founder, B2B SaaS (Fund Portfolio)",
      weight_pct: 10.8,
      background: "Founder of a $30M ARR B2B SaaS company in the fund's portfolio. Informally consulted on deals in her domain.",
      evaluation_lens: "Evaluates operational reality of the plan. Spots naive assumptions about enterprise sales cycles, customer success costs, and GTM timeline.",
      image: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_b8b4e9e6-24d2-468f-95bd-39ee687ce670.jpg",
      isRepresentative: true,
    },
    {
      key: "pf_p2",
      archetype: "Portfolio Founder",
      name: "Antoine Dubois",
      role: "Founder, Legal Tech (Fund Portfolio)",
      weight_pct: 9.6,
      background: "Founder who built and sold a legal workflow product. Has domain-specific knowledge of what works and what doesn't in legal tech.",
      evaluation_lens: "Evaluates domain assumptions with high specificity. Knows the real sales cycle for legal software, typical churn patterns, and buyer psychology.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "ms_p1",
      archetype: "Market Skeptic",
      name: "George Petrov",
      role: "Partner, Market Dynamics Focus",
      weight_pct: 10.8,
      background: "Partner who specialises in market sizing and timing. Has seen the legal AI space since 2015 and knows multiple failed attempts.",
      evaluation_lens: "Evaluates bottom-up market derivation, competitive timing, and whether this is different from prior legal AI waves.",
      image: "",
      isRepresentative: true,
    },
    {
      key: "ms_p2",
      archetype: "Market Skeptic",
      name: "Diana Webb",
      role: "Partner, Competitive Moat Specialist",
      weight_pct: 8.4,
      background: "Partner focused on defensibility and competitive dynamics. Evaluates whether the moat lasts 3–5 years or gets commoditised.",
      evaluation_lens: "Evaluates moat durability, commoditisation risk, and whether the AI advantage persists as foundation models improve.",
      image: "",
      isRepresentative: false,
    },
    {
      key: "op_p1",
      archetype: "Operational Partner",
      name: "Sandra Collins",
      role: "Operational Partner, Post-Investment",
      weight_pct: 9.6,
      background: "Operational partner who works with portfolio companies post-investment. Evaluates execution risk and capital efficiency.",
      evaluation_lens: "Evaluates whether the milestone plan is realistic given the raise amount, hiring plan coherence, and post-investment operational risks.",
      image: "https://miaoda-site-img.s3cdn.medo.dev/images/KLing_ce858c2a-42a5-432c-a0a6-9decbe3e7f82.jpg",
      isRepresentative: true,
    },
    {
      key: "op_p2",
      archetype: "Operational Partner",
      name: "Kevin Zhang",
      role: "VP of Portfolio Success",
      weight_pct: 8.4,
      background: "VP of portfolio success. Works with 20 portfolio companies post-close. Evaluates what founders actually need vs. what they're asking for.",
      evaluation_lens: "Evaluates whether the use of funds is well-planned, whether the team knows what they don't know, and post-close support requirements.",
      image: "",
      isRepresentative: false,
    },
  ],
};

export const audiencePanels: AudiencePanel[] = [
  seed_investors,
  enterprise_buyers,
  hiring_managers,
  series_a_investors,
];

export function getPanelByKey(key: string): AudiencePanel | undefined {
  return audiencePanels.find((p) => p.key === key);
}

export function getRepresentativePersonas(panel: AudiencePanel): Persona[] {
  return panel.personas.filter((p) => p.isRepresentative);
}
